name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: T0
      id: t0
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: T0
        setup-command: javac Main.java
        command: java Main < input00.txt
        input: ''
        expected-output: |
          SUM:-1
          DIFF:19
        comparison-method: contains
        timeout: 10
    - name: T1
      id: t1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: T1
        setup-command: javac Main.java
        command: java Main < input01.txt
        input: ''
        expected-output: |
          SUM:17
          DIFF:7
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T0_RESULTS: "${{steps.t0.outputs.result}}"
        T1_RESULTS: "${{steps.t1.outputs.result}}"
      with:
        runners: t0,t1
